"use client";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Loader2, Wand2 } from "lucide-react";
import { generateMockData, MockDataMode } from "@/lib/aiApi";
import { getErrorMessage } from "@/lib/errors";
import OutputBlock from "./OutputBlock";

const MODES: { value: MockDataMode; label: string; hint: string }[] = [
  { value: "SIMPLE", label: "Simple", hint: "A flat object with primitive fields." },
  { value: "NESTED", label: "Nested", hint: "Nested objects and arrays, 2-3 levels deep." },
  { value: "LARGE", label: "Large batch", hint: "An array of many realistic objects." },
  { value: "EDGE_CASES", label: "Edge cases", hint: "Boundary values: empty strings, nulls, unicode, extremes." },
  { value: "INVALID", label: "Invalid data", hint: "Deliberately malformed, for testing validation." },
  { value: "REALISTIC", label: "Realistic", hint: "Plausible, internally-consistent real-world values." },
];

export default function MockDataGeneratorTool() {
  const [description, setDescription] = useState("");
  const [mode, setMode] = useState<MockDataMode>("SIMPLE");
  const [count, setCount] = useState("10");
  const [result, setResult] = useState("");
  const [usedHeuristic, setUsedHeuristic] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    if (!description.trim()) {
      toast.error("Describe the data shape first (e.g. \"a user with id, name, email\").");
      return;
    }
    setLoading(true);
    try {
      const res = await generateMockData(description.trim(), mode, count ? Number(count) : undefined);
      setResult(res.result);
      setUsedHeuristic(res.provider === "deterministic");
    } catch (e) {
      toast.error(getErrorMessage(e, "Failed to generate mock data."));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="mock-description">Data shape</Label>
        <Textarea
          id="mock-description"
          placeholder='e.g. "a user with id, name, email, and a nested address (street, city, country)" — or paste an example JSON object.'
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          rows={3}
          className="font-mono text-xs"
        />
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-[1fr_100px] gap-3">
        <div className="space-y-2">
          <Label>Mode</Label>
          <Select value={mode} onValueChange={(v) => setMode(v as MockDataMode)}>
            <SelectTrigger><SelectValue /></SelectTrigger>
            <SelectContent>
              {MODES.map((m) => <SelectItem key={m.value} value={m.value}>{m.label}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="mock-count">Count</Label>
          <Input id="mock-count" type="number" min={1} max={100} value={count} onChange={(e) => setCount(e.target.value)} />
        </div>
      </div>
      <p className="text-xs text-muted-foreground -mt-2">{MODES.find((m) => m.value === mode)?.hint}</p>

      <Button onClick={handleGenerate} disabled={loading} className="gap-2">
        {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Wand2 className="h-4 w-4" />}
        Generate mock data
      </Button>

      {usedHeuristic && result && (
        <p className="text-xs text-muted-foreground">
          No AI provider was available, so this was generated by the built-in heuristic faker from your JSON shape.
        </p>
      )}

      <OutputBlock content={result} filename="mock-data.json" emptyLabel="Your generated JSON will appear here." minHeight="200px" />
    </div>
  );
}
